import { all, put, remove, log } from "./storage.js";
import { createUser, currentUser, hasUsers, login, logout } from "./auth.js";
import { renderUsers } from "./users.js";
import { can } from "./permissions.js";
import { renderSchema } from "./schema.js";
import { renderRelationships } from "./relationships.js";
import { renderQueryPage } from "./query-page.js";
import { renderViews } from "./views.js";
import { renderIndexes } from "./indexes.js";
import { renderTransactions } from "./transactions.js";
import { renderReports } from "./reports.js";
import { renderImportExport } from "./import-export.js";
import { renderSecurity } from "./security.js";
import { applySettings, renderSettings } from "./settings.js";
import { renderAuditPage } from "./audit-page.js";
import { renderDemo } from "./demo.js";
import "./row-editor.js";
import "./column-editor.js";
import "./row-position-editor.js";

applySettings();
const state={page:"overview",databaseId:null,tableId:null,query:""};
const icons={overview:"▦",tables:"▤",schema:"＋",data:"▥",query:"⌘",builder:"◇",relations:"⌁",views:"▧",indexes:"⌗",transactions:"↔",reports:"▥",importExport:"⇄",demo:"✦",security:"◈",settings:"⚙",audit:"◷",backup:"⇩",users:"♙"};
async function renderPage(dbs){const content=document.querySelector("#content"),user=await currentUser();if(!can(user?.role,state.page)){state.page="overview";return overview(content,dbs)}if(state.page==="schema")return renderSchema(content,{databaseId:state.databaseId,esc,toast,renderApp});if(state.page==="overview")return overview(content,dbs);if(state.page==="tables")return tables(content,dbs);if(state.page==="data")return dataPage(content);if(state.page==="query")return renderQueryPage(content,{databaseId:state.databaseId,esc});if(state.page==="builder")return queryBuilder(content);if(state.page==="backup")return backup(content,dbs);if(state.page==="audit")return renderAuditPage(content,{esc});if(state.page==="relations")return renderRelationships(content,{databaseId:state.databaseId,esc,toast,renderApp});if(state.page==="views")return renderViews(content,{databaseId:state.databaseId,esc,toast,renderApp});if(state.page==="indexes")return renderIndexes(content,{databaseId:state.databaseId,esc,toast,renderApp});if(state.page==="transactions")return renderTransactions(content,{databaseId:state.databaseId,esc,toast,renderApp});if(state.page==="reports")return renderReports(content,{databaseId:state.databaseId,esc});if(state.page==="importExport")return renderImportExport(content,{databaseId:state.databaseId,esc,toast,renderApp});if(state.page==="demo")return renderDemo(content,{esc,toast,renderApp});if(state.page==="security")return renderSecurity(content,{esc});if(state.page==="settings")return renderSettings(content);if(state.page==="users")return renderUsers(content,{esc,modal,toast});content.innerHTML=`<div class="card"><h3>Security center</h3><p class="muted">This workspace module is ready for your local schema. Select a database to begin managing records.</p></div>`
}
async function queryBuilder(el){const tables=(await all("tables")).filter((table)=>table.databaseId===state.databaseId);el.innerHTML=`<div class="toolbar"><div><div class="muted">NO-CODE QUERY BUILDER</div><h1 style="margin:4px 0">Build a query visually</h1><p class="muted">Choose fields and conditions. Fieldbase generates the SQL for you.</p></div></div><div class="card builder-card"><div class="form-grid"><div class="field"><label>TABLE</label><select id="builder-table"><option value="">Choose a table</option>${tables.map((table)=>`<option value="${table.id}">${esc(table.name)}</option>`).join("")}</select></div><div class="field"><label>LIMIT</label><input id="builder-limit" type="number" min="1" max="500" value="50"></div></div><div class="field"><label>COLUMNS</label><div class="builder-columns" id="builder-columns"><span class="muted">Choose a table to see its columns.</span></div></div><div class="builder-condition"><div class="field"><label>FILTER (OPTIONAL)</label><select id="builder-filter"><option value="">No filter</option></select></div><div class="field"><label>OPERATOR</label><select id="builder-operator"><option value="=">Equals</option><option value="!=">Does not equal</option><option value=">">Greater than</option><option value="<">Less than</option><option value="contains">Contains</option></select></div><div class="field"><label>VALUE</label><input id="builder-value" placeholder="e.g. 80"></div></div><div class="field"><label>SORT BY</label><select id="builder-sort"><option value="">No sorting</option></select></div><div class="generated-query"><span>GENERATED QUERY</span><code id="generated-query">Choose a table to begin</code></div><div class="actions"><button class="btn primary" id="run-builder">Run query →</button><button class="btn" id="clear-builder">Clear</button></div><div id="builder-result"></div></div>`;
const tableSelect=document.querySelector("#builder-table"),columnsEl=document.querySelector("#builder-columns"),filterSelect=document.querySelector("#builder-filter"),sortSelect=document.querySelector("#builder-sort"),queryEl=document.querySelector("#generated-query");let selectedColumns=[];
function selectedTable(){return tables.find((table)=>table.id===tableSelect.value)}
function refreshBuilder(){const table=selectedTable();if(!table){columnsEl.innerHTML='<span class="muted">Choose a table to see its columns.</span>';filterSelect.innerHTML='<option value="">No filter</option>';sortSelect.innerHTML='<option value="">No sorting</option>';queryEl.textContent="Choose a table to begin";return}columnsEl.innerHTML=table.columns.map((column,index)=>`<label class="column-option"><input type="checkbox" value="${esc(column.name)}" ${index<3?"checked":""}> ${esc(column.name)} <small>${esc(column.type)}</small></label>`).join("");filterSelect.innerHTML='<option value="">No filter</option>'+table.columns.map((column)=>`<option value="${esc(column.name)}">${esc(column.name)}</option>`).join("");sortSelect.innerHTML='<option value="">No sorting</option>'+table.columns.map((column)=>`<option value="${esc(column.name)}">${esc(column.name)}</option>`).join("");selectedColumns=[...columnsEl.querySelectorAll("input")].filter((input)=>input.checked).map((input)=>input.value);updateQuery()}
function updateQuery(){const table=selectedTable();if(!table){queryEl.textContent="Choose a table to begin";return}selectedColumns=[...columnsEl.querySelectorAll("input")].filter((input)=>input.checked).map((input)=>input.value);const columns=selectedColumns.length?selectedColumns.join(", "):"*";const filter=filterSelect.value;const operator=document.querySelector("#builder-operator").value;const value=document.querySelector("#builder-value").value.trim();const where=filter&&value?` WHERE ${filter} ${operator==="contains"?"LIKE":""} ${operator==="contains"?`'%${value}%'`:`'${value.replaceAll("'","''")}'`}`:"";const sort=sortSelect.value?` ORDER BY ${sortSelect.value} DESC`:"";queryEl.textContent=`SELECT ${columns} FROM ${table.name}${where}${sort} LIMIT ${document.querySelector("#builder-limit").value};`}
tableSelect.onchange=refreshBuilder;["input","change"].forEach((eventName)=>el.addEventListener(eventName,updateQuery));refreshBuilder;document.querySelector("#run-builder").onclick=async()=>{const table=selectedTable(),result=document.querySelector("#builder-result");if(!table)return result.innerHTML='<div class="notice">Choose a table first.</div>';const columns=selectedColumns.length?selectedColumns:table.columns.map((column)=>column.name);let rows=(await all("rows")).filter((row)=>row.tableId===table.id);const filter=filterSelect.value,operator=document.querySelector("#builder-operator").value,value=document.querySelector("#builder-value").value.trim();if(filter&&value)rows=rows.filter((row)=>{const actual=String(row.values[filter]??"");if(operator==="=")return actual.toLowerCase()===value.toLowerCase();if(operator==="!=")return actual.toLowerCase()!==value.toLowerCase();if(operator===">")return Number(actual)>Number(value);if(operator==="<")return Number(actual)<Number(value);return actual.toLowerCase().includes(value.toLowerCase())});if(sortSelect.value)rows.sort((left,right)=>String(right.values[sortSelect.value]??"").localeCompare(String(left.values[sortSelect.value]??""),undefined,{numeric:true}));rows=rows.slice(0,Math.max(1,Number(document.querySelector("#builder-limit").value)||50));result.innerHTML=`<div class="notice">${rows.length} row(s) returned · generated query executed locally</div><div class="table-wrap"><table class="data-table"><thead><tr>${columns.map((column)=>`<th>${esc(column)}</th>`).join("")}</tr></thead><tbody>${rows.map((row)=>`<tr>${columns.map((column)=>`<td>${esc(row.values[column]??"")}</td>`).join("")}</tr>`).join("")||'<tr><td class="empty">No matching rows.</td></tr>'}</tbody></table></div>`};document.querySelector("#clear-builder").onclick=()=>{tableSelect.value="";refreshBuilder();document.querySelector("#builder-result").innerHTML=""}}
const app=document.querySelector("#app");
const uid=()=>crypto.randomUUID();
const esc=(value="")=>String(value).replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const toast=(message)=>{const el=document.createElement("div");el.className="toast";el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2400)};
function enforceActionPermissions(user){const restricted=user?.role!=="ADMIN"?["new-db","new-table","drop"]:[];if(user?.role==="VIEWER")restricted.push("insert");restricted.forEach((id)=>{const button=document.querySelector(`#${id}`);if(button){button.disabled=true;button.title="Your role does not have permission for this action.";button.classList.add("permission-disabled")}})}
async function setup(){const user=await currentUser();if(user)return renderApp();renderLogin(!(await hasUsers()))}
function renderLogin(first,mode=first?"signup":"signin"){const signup=mode==="signup";app.innerHTML=`<main class="login"><section class="login-card"><div class="brand"><div class="brand-mark">◈</div><h1>OFFLINE DATABASE STUDIO</h1><div class="muted">Create · Manage · Query · Analyze · Secure</div><div class="offline">OFFLINE · LOCAL STORAGE</div></div><div class="auth-heading"><h2>${signup?(first?"Create your administrator account":"Create a new account"):"Welcome back"}</h2><p class="muted">${signup?(first?"Your credentials are protected locally on this device.":"Create an account to access your local studio."):"Sign in to continue to your local studio."}</p></div><form id="auth-form">${signup?'<div class="field"><label>USERNAME</label><input name="username" required autocomplete="username"></div><div class="field"><label>PASSWORD</label><input name="password" required type="password" minlength="8" autocomplete="new-password"></div><div class="field"><label>CONFIRM PASSWORD</label><input name="confirm" required type="password" minlength="8" autocomplete="new-password"></div>':'<div class="field"><label>USERNAME</label><input name="username" required autocomplete="username"></div><div class="field"><label>PASSWORD</label><input name="password" required type="password" autocomplete="current-password">'}<div class="actions"><button class="btn primary" type="submit">${signup?(first?"Create administrator":"Sign up"):"Sign in"} →</button></div><p id="auth-error" class="error" role="alert"></p></form><div class="auth-switch"><span class="muted">${signup?"Already have an account?":"Need an account?"}</span><button class="btn link-button" id="auth-switch" type="button">${signup?"Sign in":"Sign up"}</button></div></section></main>`;
document.querySelector("#auth-switch").onclick=()=>renderLogin(first,signup?"signin":"signup");document.querySelector("#auth-form").onsubmit=async(e)=>{e.preventDefault();const fd=new FormData(e.target);const error=document.querySelector("#auth-error");try{if(signup){if(fd.get("password")!==fd.get("confirm"))throw new Error("Passwords do not match.");await createUser({username:fd.get("username"),password:fd.get("password")});toast(first?"Administrator account created":"Account created")}else await login(fd.get("username"),fd.get("password"));renderApp()}catch(exception){error.textContent=exception.message}};
}
function getRoleSummary(role){if(role==="ADMIN")return "Full access: create, edit, manage users, and change workspace settings.";if(role==="EDITOR")return "Can browse data and edit records, but cannot manage users or workspace roles.";return "Read-only access: can open pages and review data, but cannot create or change records."}
async function renderApp(){const dbs=await all("databases"),user=await currentUser();if(!state.databaseId&&dbs[0])state.databaseId=dbs[0].id;const role = user?.role || "VIEWER";app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">◈</div><h1>OFFLINE DB</h1><div class="muted">STUDIO</div><div class="offline">OFFLINE</div></div><nav class="nav">${Object.entries(icons).map(([key,icon])=>`<button class="${state.page===key?"active":""}" data-page="${key}">${icon} <span>${key[0].toUpperCase()+key.slice(1)}</span></button>`).join("")}</nav><div class="side-bottom"><div class="session-panel"><button class="btn small user-panel-toggle" id="session-menu-toggle" type="button"><span class="user-badge">${esc(role)}</span><span>${esc(user?.username||"Local user")}</span></button><div class="session-menu" id="session-menu"><div class="session-row"><span class="session-label">User ID</span><strong>${esc(user?.id||"local-user")}</strong></div><div class="session-row"><span class="session-label">Role</span><strong>${esc(role)}</strong></div><div class="session-row"><span class="session-label">Access</span><span>${esc(getRoleSummary(role).split(":")[0])}</span></div><div class="mini-note">${esc(getRoleSummary(role))}</div><button class="btn small danger" id="logout" type="button">Log out</button></div></div></div></aside><main class="main"><header class="topbar"><h2>${state.page==="overview"?"Workspace overview":state.page[0].toUpperCase()+state.page.slice(1)}</h2><div class="muted">● All changes saved locally · ${esc(role)}</div></header><section class="content" id="content"></section></main></div>`;
document.querySelectorAll("[data-page]").forEach((b)=>b.onclick=()=>{state.page=b.dataset.page;renderApp()});const sessionToggle=document.querySelector("#session-menu-toggle");const sessionMenu=document.querySelector("#session-menu");if(sessionToggle&&sessionMenu){sessionMenu.classList.add("open");sessionToggle.onclick=()=>sessionMenu.classList.toggle("open");document.addEventListener("click",function closeMenu(event){if(!sessionMenu.contains(event.target)&&!sessionToggle.contains(event.target)){sessionMenu.classList.remove("open")}});}document.querySelector("#logout").onclick=async()=>{await logout();state.page="overview";state.databaseId=null;renderLogin(false)};await renderPage(dbs);enforceActionPermissions(user)}
function download(name,content,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function printDocument(title,body){const win=window.open("","_blank","width=1000,height=700");if(!win)return toast("Allow pop-ups to create a PDF");win.document.write(`<!doctype html><html><head><title>${esc(title)}</title><style>body{font:14px Arial;color:#172033;padding:32px}h1{margin-top:0}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bcc7d5;padding:8px;text-align:left}th{background:#eaf0f6}.meta{color:#5d6c7e;margin-bottom:20px}</style></head><body><h1>${esc(title)}</h1><div class="meta">Generated ${new Date().toLocaleString()} · Offline Database Studio</div>${body}</body></html>`);win.document.close();win.focus();setTimeout(()=>win.print(),250)}
function tableReport(t,rows){return `<h2>Table: ${esc(t.name)}</h2><p>${t.columns.length} columns · ${rows.length} records</p><table><thead><tr>${t.columns.map((c)=>`<th>${esc(c.name)}</th>`).join("")}</tr></thead><tbody>${rows.map((r)=>`<tr>${t.columns.map((c)=>`<td>${esc(r.values[c.name]??"")}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
async function overview(el,dbs){const tables=await all("tables"),rows=await all("rows");el.innerHTML=`<div class="toolbar"><div><div class="muted">LOCAL WORKSPACE</div><h1 style="margin:4px 0">Good to see you.</h1></div><button class="btn primary" id="new-db">＋ New database</button></div><div class="grid"><div class="card"><div class="metric">${dbs.length}</div><div class="metric-label">Databases</div></div><div class="card"><div class="metric">${tables.length}</div><div class="metric-label">Tables</div></div><div class="card"><div class="metric">${rows.length}</div><div class="metric-label">Records</div></div></div><div class="section"><div class="section-title"><h3>Your databases</h3></div><div class="grid">${dbs.length?dbs.map((db)=>`<button class="card db-card" data-db="${db.id}" style="text-align:left"><h3>◫ ${esc(db.name)}</h3><div class="muted">${esc(db.description||"Local database")} · ${new Date(db.createdAt).toLocaleDateString()}</div></button>`).join(""):`<div class="card empty">No databases yet. Create your first local database.</div>`}</div></div>`;document.querySelector("#new-db").onclick=()=>modal("Create database",`<div class="field"><label>DATABASE NAME</label><input name="name" required placeholder="e.g. inventory"></div><div class="field" style="margin-top:12px"><label>DESCRIPTION</label><input name="description" placeholder="What will you store?"></div>`,async(fd)=>{const db={id:uid(),name:fd.get("name"),description:fd.get("description"),createdAt:new Date().toISOString()};await put("databases",db);await log("Created database",db.name);state.databaseId=db.id;toast("Database created");renderApp()});document.querySelectorAll("[data-db]").forEach((b)=>b.onclick=()=>{state.databaseId=b.dataset.db;state.page="tables";renderApp()})}
async function tables(el,dbs){const db=dbs.find((x)=>x.id===state.databaseId),ts=(await all("tables")).filter((x)=>x.databaseId===state.databaseId);el.innerHTML=`<div class="toolbar"><div><div class="muted">DATABASE</div><h1 style="margin:4px 0">${esc(db?.name||"Select a database")}</h1></div><button class="btn primary" id="new-table">＋ New table</button></div><div class="grid">${ts.length?ts.map((t)=>`<button class="card table-card" data-table="${t.id}" style="text-align:left"><h3>▤ ${esc(t.name)}</h3><div class="muted">${t.columns.length} columns · ${(t.rowCount||0)} records</div></button>`).join(""):`<div class="card empty">No tables in this database. Add one to start managing records.</div>`}</div>`;document.querySelector("#new-table").onclick=()=>modal("Create table",`<div class="field"><label>TABLE NAME</label><input name="name" required placeholder="customers"></div><div class="field" style="margin-top:12px"><label>COLUMNS (comma separated)</label><input name="columns" required value="id, name, created_at"></div>`,async(fd)=>{const cols=String(fd.get("columns")).split(",").map((n,i)=>({name:n.trim(),type:i===0?"INTEGER":"TEXT"})).filter((c)=>c.name);const t={id:uid(),databaseId:state.databaseId,name:fd.get("name"),columns:cols,rowCount:0,createdAt:new Date().toISOString()};await put("tables",t);await log("Created table",t.name);toast("Table created");renderApp()});document.querySelectorAll("[data-table]").forEach((b)=>b.onclick=()=>{state.tableId=b.dataset.table;state.page="data";renderApp()})}
async function dataPage(el){const t=(await all("tables")).find((x)=>x.id===state.tableId);const rows=(await all("rows")).filter((x)=>x.tableId===t.id);el.innerHTML=`<div class="toolbar"><div><div class="muted">TABLE</div><h1 style="margin:4px 0">${esc(t.name)}</h1></div><input class="search" id="row-search" placeholder="Search records…" value="${esc(state.query)}"><button class="btn primary" id="insert">＋ Insert row</button><button class="btn" id="table-pdf">PDF</button><button class="btn" id="table-csv">CSV</button><button class="btn danger" id="drop">Drop table</button></div><div class="table-wrap">${rows.length?`<table class="data-table"><thead><tr>${t.columns.map((c)=>`<th>${esc(c.name)}</th>`).join("")}<th>Actions</th></tr></thead><tbody>${rows.filter((r)=>!state.query||JSON.stringify(r).toLowerCase().includes(state.query.toLowerCase())).map((r)=>`<tr>${t.columns.map((c)=>`<td>${esc(r.values[c.name]??"")}</td>`).join("")}<td><button class="btn small danger" data-delete="${r.id}">Delete</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No records yet. Insert your first row.</div>`}</div>`;document.querySelector("#row-search").oninput=(e)=>{state.query=e.target.value;dataPage(el)};document.querySelector("#table-pdf").onclick=()=>printDocument(`Table ${t.name}`,tableReport(t,rows));document.querySelector("#table-csv").onclick=()=>download(`${t.name}.csv`,[t.columns.map((c)=>`"${c.name.replace(/"/g,'""')}"`).join(","),...rows.map((r)=>t.columns.map((c)=>`"${String(r.values[c.name]??"").replace(/"/g,'""')}"`).join(","))].join("\r\n"),"text/csv");document.querySelector("#insert").onclick=()=>modal("Insert row",t.columns.map((c)=>`<div class="field" style="margin-top:12px"><label>${esc(c.name)} · ${c.type}</label><input name="${esc(c.name)}" ${c.name==="id"?"type=number":""}></div>`).join(""),async(fd)=>{const values={};t.columns.forEach((c)=>values[c.name]=fd.get(c.name));await put("rows",{id:uid(),tableId:t.id,values,createdAt:new Date().toISOString()});t.rowCount=(t.rowCount||0)+1;await put("tables",t);await log("Inserted row",t.name);toast("Row inserted");dataPage(el)});document.querySelector("#drop").onclick=async()=>{if(confirm(`Drop ${t.name}? This cannot be undone.`)){for(const r of rows)await remove("rows",r.id);await remove("tables",t.id);state.page="tables";toast("Table dropped");renderApp()}};document.querySelectorAll("[data-delete]").forEach((b)=>b.onclick=async()=>{await remove("rows",b.dataset.delete);t.rowCount=Math.max(0,(t.rowCount||1)-1);await put("tables",t);toast("Row deleted");dataPage(el)})}
async function queryPage(el,dbs){const ts=await all("tables");el.innerHTML=`<div class="toolbar"><div><div class="muted">SQL CONSOLE</div><h1 style="margin:4px 0">Query your local data</h1></div></div><div class="card"><div class="field"><label>SQL (supported: SELECT * FROM table)</label><textarea id="sql" rows="4" placeholder="SELECT * FROM customers"></textarea></div><div class="actions"><button class="btn primary" id="run">Run query ▶</button></div><div id="result"></div></div><div class="section"><div class="muted">AVAILABLE TABLES</div><p>${ts.map((t)=>`<span class="badge" style="margin:6px 4px 0 0">${esc(t.name)}</span>`).join("")||"No tables yet"}</p></div>`;document.querySelector("#run").onclick=async()=>{const sql=document.querySelector("#sql").value.trim().match(/^select\\s+\\*\\s+from\\s+([\\w-]+)$/i),out=document.querySelector("#result");if(!sql)return out.innerHTML='<p class="muted">Try: SELECT * FROM table_name</p>';const t=ts.find((x)=>x.name.toLowerCase()===sql[1].toLowerCase()),rs=t?(await all("rows")).filter((r)=>r.tableId===t.id):[];out.innerHTML=t?`<div class="notice">${rs.length} row(s) returned from ${esc(t.name)}</div>`:'<div class="notice">Table not found in this workspace.</div>';};}
async function backup(el,dbs){el.innerHTML=`<div class="toolbar"><div><div class="muted">DATA PORTABILITY</div><h1 style="margin:4px 0">Backup & restore</h1></div><button class="btn" id="db-pdf">PDF database report</button></div><div class="grid"><div class="card"><h3>Export workspace</h3><p class="muted">Download every database, table, row, setting and audit event as JSON.</p><button class="btn primary" id="export">⇩ Download backup</button></div><div class="card"><h3>Restore workspace</h3><p class="muted">Restore a previously exported Offline Database Studio JSON file.</p><input type="file" id="restore" accept=".json"></div></div>`;document.querySelector("#db-pdf").onclick=async()=>{const db=dbs.find((x)=>x.id===state.databaseId)||dbs[0];if(!db)return toast("Create a database first");const ts=(await all("tables")).filter((t)=>t.databaseId===db.id),rs=await all("rows");printDocument(`Database ${db.name}`,`<p>${esc(db.description||"Local database")}</p>${ts.map((t)=>tableReport(t,rs.filter((r)=>r.tableId===t.id))).join("<hr>")}`)};document.querySelector("#export").onclick=async()=>{const data={databases:await all("databases"),tables:await all("tables"),rows:await all("rows"),settings:await all("settings"),audit:await all("audit"),exportedAt:new Date().toISOString()};download("offline-database-studio-backup.json",JSON.stringify(data,null,2),"application/json");toast("Backup downloaded")};document.querySelector("#restore").onchange=async(e)=>{try{const data=JSON.parse(await e.target.files[0].text());for(const key of ["databases","tables","rows","settings","audit"])for(const value of data[key]||[])await put(key,value);toast("Workspace restored");renderApp()}catch(error){toast(`Restore failed: ${error.message}`)}}}
async function audit(el){const logs=(await all("audit")).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));el.innerHTML=`<div class="toolbar"><div><div class="muted">ACTIVITY</div><h1 style="margin:4px 0">Audit log</h1></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Action</th><th>Details</th><th>Time</th></tr></thead><tbody>${logs.map((x)=>`<tr><td>${esc(x.action)}</td><td>${esc(x.details)}</td><td>${new Date(x.createdAt).toLocaleString()}</td></tr>`).join("")||'<tr><td colspan="3" class="empty">No activity recorded.</td></tr>'}</tbody></table></div>`}
async function relations(el,dbs){const ts=(await all("tables")).filter((t)=>t.databaseId===state.databaseId);el.innerHTML=`<div class="toolbar"><div><div class="muted">SCHEMA DESIGN</div><h1 style="margin:4px 0">Relationships</h1></div><button class="btn primary" id="relations-pdf">PDF schema report</button></div><div class="notice">Relationship definitions can be documented in this offline schema report. Tables and columns are shown below.</div><div class="grid">${ts.map((t)=>`<div class="card"><h3>▤ ${esc(t.name)}</h3><ul>${t.columns.map((c)=>`<li>${esc(c.name)} <span class="muted">${esc(c.type)}</span></li>`).join("")}</ul></div>`).join("")||'<div class="card empty">Select a database with tables to view its schema.</div>'}</div>`;document.querySelector("#relations-pdf").onclick=()=>printDocument("Relationship and schema report",`<h2>Database: ${esc(dbs.find((d)=>d.id===state.databaseId)?.name||"Workspace")}</h2>${ts.map((t)=>`<h3>${esc(t.name)}</h3><ul>${t.columns.map((c)=>`<li>${esc(c.name)} (${esc(c.type)})</li>`).join("")}</ul>`).join("")}`)}
function modal(title,body,onSubmit){const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<div class="modal"><h2>${title}</h2><form>${body}<p class="error" data-modal-error role="alert"></p><div class="actions"><button type="button" class="btn" data-cancel>Cancel</button><button class="btn primary">Save</button></div></form></div>`;document.body.append(wrap);wrap.querySelector("[data-cancel]").onclick=()=>wrap.remove();wrap.querySelector("form").onsubmit=async(e)=>{e.preventDefault();try{await onSubmit(new FormData(e.target));wrap.remove()}catch(error){wrap.querySelector("[data-modal-error]").textContent=error.message}}}
setup();
