import { all, log, put } from "./storage.js";

const demoTables = [
  { name: "Students", columns: [{ name: "student_id", type: "INTEGER", primaryKey: true, notNull: true }, { name: "name", type: "VARCHAR", notNull: true }, { name: "age", type: "INTEGER" }, { name: "marks", type: "DECIMAL" }, { name: "email", type: "VARCHAR", unique: true }] },
  { name: "Courses", columns: [{ name: "course_id", type: "INTEGER", primaryKey: true, notNull: true }, { name: "course_name", type: "VARCHAR", notNull: true }] },
  { name: "Departments", columns: [{ name: "department_id", type: "INTEGER", primaryKey: true, notNull: true }, { name: "department_name", type: "VARCHAR", notNull: true }] },
];

export async function renderDemo(el, { esc, toast, renderApp }) {
  el.innerHTML = `<div class="toolbar"><div><div class="muted">START WITH A REAL DATASET</div><h1 style="margin:4px 0">Load demo database</h1><p class="muted">Explore the no-code workflow with a small college management dataset.</p></div></div><div class="card demo-card"><span class="badge">COLLEGEDB</span><h2>College management, ready to explore</h2><p class="muted">Students, courses, and departments with relationships and sample rows. Loading the demo creates a separate local database and does not modify your existing data.</p><ul><li>3 tables</li><li>11 columns</li><li>10 sample records</li><li>2 relationships</li></ul><button class="btn primary" id="load-demo">Create demo database →</button><p class="error" id="demo-error" role="alert"></p></div>`;
  document.querySelector("#load-demo").onclick = async () => { try { if ((await all("databases")).some((database) => database.name === "CollegeDB")) throw new Error("CollegeDB already exists in this workspace."); const database = { id: crypto.randomUUID(), name: "CollegeDB", description: "College management demo database", createdAt: new Date().toISOString() }; await put("databases", database); const tables = {}; for (const definition of demoTables) { const table = { id: crypto.randomUUID(), databaseId: database.id, name: definition.name, columns: definition.columns, rowCount: 0, createdAt: new Date().toISOString() }; tables[table.name] = table; await put("tables", table); } const sample = [{ table: "Students", values: { student_id: "1", name: "Rahul", age: "20", marks: "85", email: "rahul@example.com" } }, { table: "Students", values: { student_id: "2", name: "Aman", age: "21", marks: "78", email: "aman@example.com" } }, { table: "Students", values: { student_id: "3", name: "Ravi", age: "20", marks: "90", email: "ravi@example.com" } }, { table: "Students", values: { student_id: "4", name: "Suresh", age: "22", marks: "88", email: "suresh@example.com" } }, { table: "Courses", values: { course_id: "101", course_name: "Python" } }, { table: "Courses", values: { course_id: "102", course_name: "Java" } }, { table: "Courses", values: { course_id: "103", course_name: "C++" } }, { table: "Courses", values: { course_id: "104", course_name: "Database" } }, { table: "Departments", values: { department_id: "1", department_name: "Computer Science" } }, { table: "Departments", values: { department_id: "2", department_name: "Information Technology" } }]; for (const item of sample) await put("rows", { id: crypto.randomUUID(), tableId: tables[item.table].id, values: item.values, createdAt: new Date().toISOString() }); await put("relationships", { id: crypto.randomUUID(), databaseId: database.id, sourceTableId: tables.Students.id, sourceColumn: "student_id", targetTableId: tables.Courses.id, targetColumn: "course_id", type: "ONE_TO_MANY", createdAt: new Date().toISOString() }); await put("relationships", { id: crypto.randomUUID(), databaseId: database.id, sourceTableId: tables.Students.id, sourceColumn: "student_id", targetTableId: tables.Departments.id, targetColumn: "department_id", type: "ONE_TO_MANY", createdAt: new Date().toISOString() }); await log("Loaded demo database", database.name); toast("CollegeDB loaded"); renderApp(); } catch (error) { document.querySelector("#demo-error").textContent = error.message; } };
}
