import { all, log, put } from "./storage.js";

function parseCsv(text) {
  const lines = text.trim().split(/\r?\n/).filter(Boolean);
  if (!lines.length) throw new Error("The CSV file is empty.");
  return lines.map((line) => line.split(",").map((cell) => cell.trim().replace(/^"|"$/g, "")));
}

export async function renderImportExport(el, { databaseId, esc, toast, renderApp }) {
  const tables = (await all("tables")).filter((table) => table.databaseId === databaseId);
  el.innerHTML = `<div class="toolbar"><div><div class="muted">DATA PORTABILITY</div><h1 style="margin:4px 0">Import / export</h1><p class="muted">Move CSV data into a table after reviewing the first rows.</p></div></div><div class="grid"><div class="card"><h3>Import CSV</h3><p class="muted">The first row must contain column names matching your table.</p><div class="field"><label>TARGET TABLE</label><select id="import-table"><option value="">Choose a table</option>${tables.map((table) => `<option value="${table.id}">${esc(table.name)}</option>`).join("")}</select></div><div class="field"><label>CSV FILE</label><input id="import-file" type="file" accept=".csv,text/csv"></div><div id="import-preview"></div><button class="btn primary" id="confirm-import" disabled>Import rows</button><p class="error" id="import-error" role="alert"></p></div><div class="card"><h3>Export CSV</h3><p class="muted">Download the current contents of a table as a portable CSV file.</p><div class="field"><label>SOURCE TABLE</label><select id="export-table"><option value="">Choose a table</option>${tables.map((table) => `<option value="${table.id}">${esc(table.name)}</option>`).join("")}</select></div><button class="btn" id="export-csv">Download CSV</button></div></div>`;
  let parsedRows = [];
  const fileInput = document.querySelector("#import-file"), tableSelect = document.querySelector("#import-table"), preview = document.querySelector("#import-preview"), confirm = document.querySelector("#confirm-import");
  fileInput.onchange = async () => { try { parsedRows = parseCsv(await fileInput.files[0].text()); if (!tableSelect.value) throw new Error("Choose a target table first."); preview.innerHTML = `<div class="notice">${parsedRows.length - 1} row(s) detected</div><pre class="csv-preview">${esc(parsedRows.slice(0, 4).map((row) => row.join(" | ")).join("\n"))}</pre>`; confirm.disabled = false; } catch (error) { document.querySelector("#import-error").textContent = error.message; confirm.disabled = true; } };
  confirm.onclick = async () => { const table = tables.find((item) => item.id === tableSelect.value), headers = parsedRows[0]; try { if (!table) throw new Error("Choose a target table."); const expected = table.columns.map((column) => column.name); if (headers.some((header) => !expected.includes(header))) throw new Error("CSV headers must match the target table columns."); for (const cells of parsedRows.slice(1)) { const values = Object.fromEntries(headers.map((header, index) => [header, cells[index] ?? ""])); await put("rows", { id: crypto.randomUUID(), tableId: table.id, values, createdAt: new Date().toISOString() }); } await log("Imported CSV", `${parsedRows.length - 1} rows into ${table.name}`); toast("CSV imported successfully"); renderApp(); } catch (error) { document.querySelector("#import-error").textContent = error.message; } };
  document.querySelector("#export-csv").onclick = async () => { const table = tables.find((item) => item.id === document.querySelector("#export-table").value); if (!table) { toast("Choose a table first"); return; } const rows = (await all("rows")).filter((row) => row.tableId === table.id), csv = [table.columns.map((column) => column.name).join(","), ...rows.map((row) => table.columns.map((column) => `"${String(row.values[column.name] ?? "").replaceAll('"', '""')}"`).join(","))].join("\r\n"), link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `${table.name}.csv`; link.click(); URL.revokeObjectURL(link.href); await log("Exported CSV", table.name); toast("CSV export ready"); };
}
