import { all, log, put, remove } from "./storage.js";
import { currentUser } from "./auth.js";

export async function renderIndexes(el, { databaseId, esc, toast, renderApp }) {
  const tables = (await all("tables")).filter((table) => table.databaseId === databaseId);
  const indexes = (await all("indexes")).filter((index) => index.databaseId === databaseId);
  el.innerHTML = `<div class="toolbar"><div><div class="muted">PERFORMANCE METADATA</div><h1 style="margin:4px 0">Indexes</h1><p class="muted">Document frequently searched fields. Browser storage treats these as simulated indexes.</p></div><button class="btn primary" id="new-index">＋ Create index</button></div><div class="card"><table class="data-table"><thead><tr><th>Index</th><th>Table</th><th>Column</th><th>Status</th><th></th></tr></thead><tbody>${indexes.map((index) => { const table = tables.find((item) => item.id === index.tableId); return `<tr><td><strong>${esc(index.name)}</strong></td><td>${esc(table?.name || "Unknown")}</td><td>${esc(index.column)}</td><td><span class="status-pill active"><span></span>SIMULATED</span></td><td><button class="btn small danger" data-delete-index="${index.id}">Delete</button></td></tr>`; }).join("") || '<tr><td colspan="5" class="empty">No indexes defined yet.</td></tr>'}</tbody></table></div>`;
  document.querySelector("#new-index").onclick = async () => {
    if ((await currentUser())?.role === "VIEWER") { toast("Viewer accounts cannot create indexes"); return; }
    const options = tables.map((table) => `<option value="${table.id}">${esc(table.name)}</option>`).join("");
    const wrap = document.createElement("div"); wrap.className = "modal-backdrop"; wrap.innerHTML = `<div class="modal"><h2>Create index</h2><form><div class="field"><label>INDEX NAME</label><input name="name" required pattern="[A-Za-z_][A-Za-z0-9_]*" placeholder="idx_customers_email"></div><div class="field"><label>TABLE</label><select name="table">${options}</select></div><div class="field"><label>COLUMN</label><select name="column"></select></div><p class="error" data-index-error role="alert"></p><div class="actions"><button type="button" class="btn" data-cancel>Cancel</button><button class="btn primary">Save index</button></div></form></div>`;
    document.body.append(wrap); const form = wrap.querySelector("form"), tableSelect = form.querySelector('[name="table"]'), columnSelect = form.querySelector('[name="column"]'); const refreshColumns = () => { const table = tables.find((item) => item.id === tableSelect.value); columnSelect.innerHTML = table?.columns.map((column) => `<option>${esc(column.name)}</option>`).join("") || ""; }; tableSelect.onchange = refreshColumns; refreshColumns(); wrap.querySelector("[data-cancel]").onclick = () => wrap.remove();
    form.onsubmit = async (event) => { event.preventDefault(); const data = new FormData(form), name = data.get("name").trim(); try { if ((await all("indexes")).some((index) => index.databaseId === databaseId && index.name.toLowerCase() === name.toLowerCase())) throw new Error("That index name already exists."); await put("indexes", { id: crypto.randomUUID(), databaseId, name, tableId: data.get("table"), column: data.get("column"), createdAt: new Date().toISOString(), simulated: true }); await log("Created index", name); wrap.remove(); toast("Index created"); renderApp(); } catch (error) { wrap.querySelector("[data-index-error]").textContent = error.message; } };
  };
  document.querySelectorAll("[data-delete-index]").forEach((button) => { button.onclick = async () => { if ((await currentUser())?.role === "VIEWER") { toast("Viewer accounts cannot delete indexes"); return; } if (!window.confirm("Delete this index?")) return; await remove("indexes", button.dataset.deleteIndex); await log("Deleted index", button.dataset.deleteIndex); toast("Index deleted"); renderApp(); }; });
}
