import { all, log, put, remove } from "./storage.js";

export async function renderRelationships(el, { databaseId, esc, toast, renderApp }) {
  const tables = (await all("tables")).filter((table) => table.databaseId === databaseId);
  const relationships = (await all("relationships")).filter((item) => item.databaseId === databaseId);
  el.innerHTML = `<div class="toolbar"><div><div class="muted">SCHEMA DESIGN</div><h1 style="margin:4px 0">Relationships</h1><p class="muted">Connect tables and keep linked data understandable.</p></div><button class="btn primary" id="new-relationship">＋ Add relationship</button></div><div class="grid relationship-grid">${relationships.map((relationship) => { const source = tables.find((table) => table.id === relationship.sourceTableId), target = tables.find((table) => table.id === relationship.targetTableId); return `<div class="card relationship-card"><span class="relationship-type">${esc(relationship.type)}</span><h3>${esc(source?.name || "Unknown table")} <span>→</span> ${esc(target?.name || "Unknown table")}</h3><p class="muted">${esc(relationship.sourceColumn)} references ${esc(relationship.targetColumn)}</p><button class="btn small danger" data-remove-relationship="${relationship.id}">Remove</button></div>`; }).join("") || '<div class="card empty">No relationships yet. Connect two tables to model how their data belongs together.</div>'}</div>`;
  document.querySelector("#new-relationship").onclick = () => {
    if (tables.length < 2) { toast("Create at least two tables first"); return; }
    const options = tables.map((table) => `<option value="${table.id}">${esc(table.name)}</option>`).join("");
    const fields = (table) => table?.columns.map((column) => `<option>${esc(column.name)}</option>`).join("") || "";
    const wrap = document.createElement("div");
    wrap.className = "modal-backdrop";
    wrap.innerHTML = `<div class="modal"><h2>Connect tables</h2><form><div class="field"><label>RELATIONSHIP TYPE</label><select name="type"><option>ONE_TO_MANY</option><option>ONE_TO_ONE</option><option>MANY_TO_MANY</option></select></div><div class="field"><label>SOURCE TABLE</label><select name="sourceTable">${options}</select></div><div class="field"><label>SOURCE COLUMN</label><select name="sourceColumn">${fields(tables[0])}</select></div><div class="field"><label>TARGET TABLE</label><select name="targetTable">${options}</select></div><div class="field"><label>TARGET COLUMN</label><select name="targetColumn">${fields(tables[1] || tables[0])}</select></div><p class="error" data-modal-error role="alert"></p><div class="actions"><button type="button" class="btn" data-cancel>Cancel</button><button class="btn primary">Save relationship</button></div></form></div>`;
    document.body.append(wrap);
    const form = wrap.querySelector("form"), sourceTable = form.querySelector('[name="sourceTable"]'), targetTable = form.querySelector('[name="targetTable"]');
    function refreshFields() { form.querySelector('[name="sourceColumn"]').innerHTML = fields(tables.find((table) => table.id === sourceTable.value)); form.querySelector('[name="targetColumn"]').innerHTML = fields(tables.find((table) => table.id === targetTable.value)); }
    sourceTable.onchange = refreshFields; targetTable.onchange = refreshFields; wrap.querySelector("[data-cancel]").onclick = () => wrap.remove();
    form.onsubmit = async (event) => { event.preventDefault(); const data = new FormData(form); if (sourceTable.value === targetTable.value) { wrap.querySelector("[data-modal-error]").textContent = "Choose two different tables."; return; } const relationship = { id: crypto.randomUUID(), databaseId, sourceTableId: sourceTable.value, sourceColumn: data.get("sourceColumn"), targetTableId: targetTable.value, targetColumn: data.get("targetColumn"), type: data.get("type"), createdAt: new Date().toISOString() }; await put("relationships", relationship); await log("Created relationship", `${relationship.sourceColumn} → ${relationship.targetColumn}`); wrap.remove(); toast("Relationship created"); renderApp(); };
  };
  document.querySelectorAll("[data-remove-relationship]").forEach((button) => { button.onclick = async () => { if (!window.confirm("Remove this relationship?")) return; await remove("relationships", button.dataset.removeRelationship); await log("Removed relationship", button.dataset.removeRelationship); toast("Relationship removed"); renderApp(); }; });
}
