import { all, log, put, remove } from "./storage.js";
import { currentUser } from "./auth.js";

const TRANSACTION_ID = "active";

export async function renderTransactions(el, { databaseId, esc, toast, renderApp }) {
  const user = await currentUser();
  if (user?.role === "VIEWER") { el.innerHTML = '<div class="card"><h3>Editor access required</h3><p class="muted">Viewer accounts can inspect data but cannot manage transactions.</p></div>'; return; }
  const tables = (await all("tables")).filter((table) => table.databaseId === databaseId);
  const active = (await all("transactions")).find((transaction) => transaction.id === TRANSACTION_ID && transaction.databaseId === databaseId);
  el.innerHTML = `<div class="toolbar"><div><div class="muted">ATOMIC WORKFLOWS</div><h1 style="margin:4px 0">Transaction manager</h1><p class="muted">Stage changes locally, then commit them or restore the previous snapshot.</p></div></div><div class="card transaction-card"><span class="status-pill ${active ? "invited" : "active"}"><span></span>${active ? "TRANSACTION ACTIVE" : "NO ACTIVE TRANSACTION"}</span>${active ? `<h3>Transaction ${esc(active.transactionNumber)}</h3><p class="muted">Snapshot created ${new Date(active.createdAt).toLocaleString()} across ${active.snapshot.length} records.</p><div class="actions"><button class="btn primary" id="commit">Commit changes</button><button class="btn danger" id="rollback">Rollback</button></div>` : `<p class="muted">A transaction captures the current rows in this database before changes are made.</p><button class="btn primary" id="begin">Begin transaction</button>`}</div><div class="card"><h3>ACID basics</h3><div class="grid"><div><strong>Atomicity</strong><p class="muted">All staged changes commit together or roll back.</p></div><div><strong>Consistency</strong><p class="muted">Validation rules still apply to every row write.</p></div><div><strong>Isolation</strong><p class="muted">The snapshot is isolated until you choose an outcome.</p></div><div><strong>Durability</strong><p class="muted">Committed rows remain in IndexedDB after reload.</p></div></div></div>`;
  document.querySelector("#begin")?.addEventListener("click", async () => { const rows = (await all("rows")).filter((row) => tables.some((table) => table.id === row.tableId)); await put("transactions", { id: TRANSACTION_ID, databaseId, transactionNumber: `TXN-${Date.now().toString().slice(-6)}`, snapshot: rows, createdAt: new Date().toISOString() }); await log("Began transaction", databaseId); toast("Transaction started"); renderApp(); });
  document.querySelector("#commit")?.addEventListener("click", async () => { await remove("transactions", TRANSACTION_ID); await log("Committed transaction", databaseId); toast("Transaction committed"); renderApp(); });
  document.querySelector("#rollback")?.addEventListener("click", async () => { if (!window.confirm("Rollback all changes made since this transaction began?")) return; const snapshot = active.snapshot; const currentRows = (await all("rows")).filter((row) => tables.some((table) => table.id === row.tableId)); for (const row of currentRows) await remove("rows", row.id); for (const row of snapshot) await put("rows", row); await remove("transactions", TRANSACTION_ID); await log("Rolled back transaction", databaseId); toast("Transaction rolled back"); renderApp(); });
}
