import { all, log, put, remove } from "./storage.js";
import { executeSelect } from "./query-engine.js";
import { currentUser } from "./auth.js";

export async function renderViews(el, { databaseId, esc, toast, renderApp }) {
  const tables = (await all("tables")).filter((table) => table.databaseId === databaseId);
  const savedViews = (await all("views")).filter((view) => view.databaseId === databaseId);
  el.innerHTML = `<div class="toolbar"><div><div class="muted">SAVED DATA PRODUCTS</div><h1 style="margin:4px 0">Views</h1><p class="muted">Save repeatable queries that always reflect your current data.</p></div><button class="btn primary" id="new-view">＋ Create view</button></div><div class="grid">${savedViews.map((view) => `<article class="card"><span class="badge">VIEW</span><h3>${esc(view.name)}</h3><code class="view-sql">${esc(view.sql)}</code><div class="actions"><button class="btn small" data-run-view="${view.id}">Run view</button><button class="btn small danger" data-delete-view="${view.id}">Delete</button></div><div id="view-result-${view.id}"></div></article>`).join("") || '<div class="card empty">No saved views yet. Create one from a SELECT query.</div>'}</div>`;
  document.querySelector("#new-view").onclick = async () => {
    if ((await currentUser())?.role === "VIEWER") { toast("Viewer accounts can run views but cannot create them"); return; }
    const options = tables.map((table) => `<option>${esc(table.name)}</option>`).join("");
    const wrap = document.createElement("div"); wrap.className = "modal-backdrop";
    wrap.innerHTML = `<div class="modal"><h2>Create view</h2><form><div class="field"><label>VIEW NAME</label><input name="name" required pattern="[A-Za-z_][A-Za-z0-9_]*" placeholder="top_customers"></div><div class="field"><label>SELECT QUERY</label><textarea name="sql" rows="5" required placeholder="SELECT * FROM customers ORDER BY id DESC LIMIT 25"></textarea></div><p class="error" data-modal-error role="alert"></p><div class="actions"><button type="button" class="btn" data-cancel>Cancel</button><button class="btn primary">Save view</button></div></form></div>`;
    document.body.append(wrap); wrap.querySelector("[data-cancel]").onclick = () => wrap.remove();
    wrap.querySelector("form").onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget), name = form.get("name").trim(), sql = form.get("sql").trim(); try { const tableName = sql.match(/\bFROM\s+([A-Za-z_][A-Za-z0-9_]*)/i)?.[1], table = tables.find((candidate) => candidate.name.toLowerCase() === tableName?.toLowerCase()); if (!table) throw new Error("The query must reference an existing table."); executeSelect(sql, table, (await all("rows")).filter((row) => row.tableId === table.id)); if ((await all("views")).some((view) => view.databaseId === databaseId && view.name.toLowerCase() === name.toLowerCase())) throw new Error("That view name already exists."); await put("views", { id: crypto.randomUUID(), databaseId, name, sql, createdAt: new Date().toISOString() }); await log("Created view", name); wrap.remove(); toast("View saved"); renderApp(); } catch (error) { wrap.querySelector("[data-modal-error]").textContent = error.message; } };
  };
  document.querySelectorAll("[data-run-view]").forEach((button) => { button.onclick = async () => { const view = savedViews.find((item) => item.id === button.dataset.runView), tableName = view.sql.match(/\bFROM\s+([A-Za-z_][A-Za-z0-9_]*)/i)?.[1], table = tables.find((candidate) => candidate.name.toLowerCase() === tableName?.toLowerCase()), output = executeSelect(view.sql, table, (await all("rows")).filter((row) => row.tableId === table.id)), target = document.querySelector(`#view-result-${view.id}`); target.innerHTML = `<div class="notice">${output.rows.length} row(s) returned</div>`; }; });
  document.querySelectorAll("[data-delete-view]").forEach((button) => { button.onclick = async () => { if ((await currentUser())?.role === "VIEWER") { toast("Viewer accounts cannot delete views"); return; } if (!window.confirm("Delete this saved view?")) return; await remove("views", button.dataset.deleteView); await log("Deleted view", button.dataset.deleteView); toast("View deleted"); renderApp(); }; });
}
